//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MusiqueSender.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package org.example.SOUP;

interface _Marker
{
}
