//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `MusiqueReceiver.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package org.example.SOUP;

/** @hidden */
public class _MusiqueSenderPrxI extends com.zeroc.Ice._ObjectPrxI implements MusiqueSenderPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
